spring:
  datasource:
    url: jdbc:mariadb://localhost:3306/product_service?serverTimezone=Asia/Seoul
    username: root
    password: qwer1234!
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
